import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({console,Date,Set});
vm.runInContext(fs.readFileSync('backtest.js','utf8'),ctx);
const source=fs.readFileSync('backtest.js','utf8');
const workspaceCss=fs.readFileSync('workspace-ui.css','utf8');
const bar=(date,adj,c=adj)=>({t:Date.parse(date+'T12:00:00Z')/1000,adj,c});
const rows=[bar('2020-01-02',100),bar('2020-01-15',90),bar('2020-02-03',120),bar('2020-02-04',120)];
const r=ctx.btCalculate(rows,1000,100,1);
assert.equal(r.paid,1100,'Monthly contribution begins next month and occurs once');
assert.equal(r.fees,11);assert.ok(Math.abs(r.value-1287)<1e-8);
assert.ok(Math.abs(r.mdd+.1)<1e-8,'Drawdown is independent of deposits');
assert.equal(r.points.length,4);
assert.equal(ctx.btCalculate([...rows,rows[0]],1000,100,1).value,r.value,'Duplicate dates do not create contributions');
const split=ctx.btCalculate([bar('2020-01-02',50,100),bar('2021-01-02',50,50)],1000,0,0);
assert.equal(split.roi,0,'Raw price split must not create a false loss');
assert.equal(split.cagr,0);
for(const input of [[NaN,0,0],[0,0,0],[100,-1,0],[100,0,6]])assert.throws(()=>ctx.btCalculate(rows,...input));
assert.throws(()=>ctx.btCalculate([rows[0],{...rows[1],adj:null}],100,0,0));
assert.throws(()=>ctx.btCalculate([rows[0]],100,0,0));
assert.equal(rows[0].adj,100,'Simulation never mutates source prices');
assert.doesNotMatch(source, />종목 검색<\/button>/, '별도 검색 버튼 없이 입력으로 자동 검색');
assert.match(source, /setTimeout\(btSearch,350\)/, '종목 입력 자동 검색은 타이핑이 멈춘 뒤 실행');
assert.match(source, /class="bt-controls"><label class="bt-query-field"[\s\S]*id="bt-range"[\s\S]*id="bt-initial"[\s\S]*id="bt-monthly"[\s\S]*id="bt-fee"[\s\S]*id="bt-run"/, '백테스트 입력과 실행 버튼을 한 컨트롤 행에 배치');
assert.match(source, /class="bt-y-tick"[\s\S]*class="bt-y-title"[\s\S]*평가금액/, '그래프에 평가금액 Y축 눈금과 제목 표시');
assert.match(workspaceCss, /\.bt-controls\{[^}]*grid-template-columns:[^}]*minmax\(160px,1\.6fr\)[^}]*88px[^}]*auto/, '데스크톱 백테스트 컨트롤을 한 줄 6열로 유지');
assert.match(workspaceCss, /@keyframes bt-chart-reveal/, '백테스트 결과 선 렌더링 애니메이션 제공');
console.log('PASS historical backtest cash flows, fees, adjusted prices, drawdown and invalid data');
