import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({console,Date,Map,Set,window:{},cbStrip:t=>String(t||'').replace(/\.(KS|KQ)$/,'')});
vm.runInContext(fs.readFileSync('etf-explorer.js','utf8'),ctx);
const s=(holdings,extra={})=>({name:'Fund',asOf:'2026-09-07',source:'provider',coverage:'full',holdings,...extra});
const h=(t,w)=>({t,n:t,w});
const now=new Date('2026-09-09T04:00:00Z');
assert.equal(ctx.etfQuality(s([h('A',50)]),now).reliable,true);
assert.equal(ctx.etfQuality(s([h('A',50)],{coverage:'partial'}),now).reliable,false);
assert.equal(ctx.etfQuality(s([h('A',50)],{asOf:null}),now).age,null);
assert.equal(ctx.etfQuality(s([h('A',50)],{retained:true}),now).reliable,false);
assert.equal(ctx.etfQuality(s([h('A',50)],{asOf:'2026-09-03',active:true}),now).stale,true);
assert.equal(ctx.etfQuality(s([h('A',50)],{asOf:'2026-09-03'}),now).stale,false);
assert.equal(ctx.etfBusinessAge('2026-09-04',new Date('2026-09-07T03:00:00Z')),1);
assert.equal(ctx.etfQuality(s([{t:'ESU6',n:'S&P500 EMINI FUT SEPT2026',w:8}]),now).rows.length,0);
assert.equal(ctx.etfQuality(s([h('A',NaN)]),now).reliable,false);
const old=s([h('A',30),h('B',20)]),current=s([h('A',35),h('C',10)],{asOf:'2026-09-08'});
let d=ctx.etfCompareSnapshots(current,old);
assert.equal(d.complete,true);assert.equal(d.rows.find(x=>x.t==='B').kind,'편출');assert.equal(d.rows.find(x=>x.t==='C').kind,'편입');
assert.equal(d.rows.find(x=>x.t==='A').delta,5);assert.equal(d.rows.find(x=>x.t==='A').w,35,'No renormalization to 100%');
d=ctx.etfCompareSnapshots({...current,coverage:'partial'},old);
assert.equal(d.complete,false);assert.equal(d.rows.length,1,'Partial lists only compare shared tickers');
assert.equal(ctx.etfCompareSnapshots({...current,source:'other'},old).comparable,false);
assert.equal(ctx.etfCompareSnapshots(current,null).rows.length,0);
assert.equal(ctx.etfCompareSnapshots(current,current).rows.length,0);
const cobalt=fs.readFileSync('cobalt.js','utf8');
const loader=cobalt.slice(cobalt.indexOf('async function cbEnsureEtfHoldings('),cobalt.indexOf('\nfunction cbIsEtf('));
let requests=0,fail=false;
const good={etfs:{F:current}};
const loadContext=vm.createContext({window:{},AbortController,setTimeout,clearTimeout,cbRerender(){},
  fetch:async()=>{requests++;if(fail)throw new Error('offline');return {ok:true,json:async()=>good};}});
vm.runInContext('let _cbEtfLoading=false;'+loader,loadContext);
await loadContext.cbEnsureEtfHoldings();assert.equal(requests,1);assert.equal(loadContext.window._etfHoldings,good);
await loadContext.cbEnsureEtfHoldings();assert.equal(requests,1,'Do not fetch again on every rerender');
fail=true;await loadContext.cbEnsureEtfHoldings(true);
assert.equal(loadContext.window._etfHoldings,good,'Failed refresh preserves the last valid file');
assert.equal(loadContext.window._etfLoadError,true);
fail=false;await loadContext.cbEnsureEtfHoldings(true);
assert.equal(requests,3);assert.equal(loadContext.window._etfLoadError,false,'Manual retry recovers');
console.log('PASS ETF freshness, active thresholds, source-aware changes and partial-list safeguards');
