import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {load} from 'cheerio';
const ctx=vm.createContext({console,Date,Map,Set,window:{},cbStrip:t=>String(t||'').replace(/\.(KS|KQ)$/,'')});
vm.runInContext(fs.readFileSync('etf-explorer.js','utf8'),ctx);
const s=(holdings,extra={})=>({name:'Fund',asOf:'2026-09-07',source:'provider',coverage:'full',holdings,...extra});
const h=(t,w)=>({t,n:t,w});
const now=new Date('2026-09-09T04:00:00Z');
assert.equal(ctx.etfQuality(s([h('A',50)]),now).reliable,true);
assert.equal(ctx.etfQuality(s([h('A',50)],{coverage:'partial'}),now).reliable,false);
assert.equal(ctx.etfQuality(s([h('A',50)],{asOf:null}),now).age,null);
assert.equal(ctx.etfQuality(s([h('A',50)],{retained:true}),now).reliable,false);
assert.equal(ctx.etfQuality(s([h('A',50)],{asOf:'2026-09-03',active:true}),now).stale,true);
assert.equal(ctx.etfQuality(s([h('A',50)],{asOf:'2026-09-03'}),now).stale,false);
assert.equal(ctx.etfBusinessAge('2026-09-04',new Date('2026-09-07T03:00:00Z')),1);
assert.equal(ctx.etfQuality(s([{t:'ESU6',n:'S&P500 EMINI FUT SEPT2026',w:8}]),now).rows.length,0);
assert.equal(ctx.etfQuality(s([h('A',NaN)]),now).reliable,false);
const old=s([h('A',30),h('B',20)]),current=s([h('A',35),h('C',10)],{asOf:'2026-09-08'});
let d=ctx.etfCompareSnapshots(current,old);
assert.equal(d.complete,true);assert.equal(d.rows.find(x=>x.t==='B').kind,'편출');assert.equal(d.rows.find(x=>x.t==='C').kind,'편입');
assert.equal(d.rows.find(x=>x.t==='A').delta,5);assert.equal(d.rows.find(x=>x.t==='A').w,35,'No renormalization to 100%');
d=ctx.etfCompareSnapshots({...current,coverage:'partial'},old);
assert.equal(d.complete,false);assert.equal(d.rows.length,1,'Partial lists only compare shared tickers');
assert.equal(ctx.etfCompareSnapshots({...current,source:'other'},old).comparable,false);
assert.equal(ctx.etfCompareSnapshots(current,null).rows.length,0);
assert.equal(ctx.etfCompareSnapshots(current,current).rows.length,0);
ctx.window._krStocksDB={byCode:new Map([['005930',{name:'삼성전자'}],['005935',{name:'삼성전자우'}]])};
ctx.pfolioData=[];
ctx.cbEsc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
ctx.cbDisp=value=>'₩'+value;
assert.equal(ctx.etfIdentity({t:'005930.KS',n:'SAMSUNG (005930)'}).name,'삼성전자');
assert.equal(ctx.etfIdentity({t:'005935',n:'SAMSUNG'}).name,'삼성전자우','Distinct Korean share classes keep their own company names');
assert.equal(ctx.etfIdentity({t:'005930',n:'삼성전자'}).showTicker,false);
for(const name of ['NVIDIA (NVDA)','NVIDIA · NVDA','NVIDIA NVDA']){
  const html=ctx.etfIdentityHtml({t:'NVDA',n:name}),$=load(html);
  assert.equal($('.etf-company b').text(),'NVIDIA');
  assert.equal($('.etf-company small').text(),'NVDA');
  assert.equal(($.text().match(/NVDA/g)||[]).length,1,'Ticker is rendered once beside the company');
}
assert.equal(load(ctx.etfIdentityHtml({t:'X',n:'<img src=x onerror=alert(1)>'}))('img').length,0);
const bars=load(ctx.etfRankChart([h('A',5),h('B',20),h('C',10)]));
assert.equal(bars('.etf-rank-row').first().attr('data-etf-ticker'),'B');
assert.equal(bars('.etf-rank-row').first().find('strong').text(),'20.00%','Bars keep original NAV weights');
assert.equal(bars('canvas').length,0,'The graph never swaps to a WebGL canvas');
const row=(owner,tkr,val,etf=false,grp='주식')=>({i:{owner,tkr,grp,etf},title:tkr,val});
ctx.cbIsEtf=i=>i.etf;
const portfolio=[row('본인','NVDA',200),row('본인','F',100,true),row('본인','F',300,true),row('본인','KRW',200,false,'현금'),row('본인','BTC',100,false,'가상화폐'),row('본인','GOLD',100,false,'금'),row('아내','F',2000,true),row('아내','NVDA',1000)];
const data={etfs:{F:s([h('NVDA',20),h('005930',10)])}};
const saved=JSON.stringify({portfolio,data});
let exposures=ctx.etfExposure('NVDA',portfolio,data,'전체',now),self=exposures.find(o=>o.owner==='본인'),spouse=exposures.find(o=>o.owner==='아내');
assert.equal(self.total,1000,'ETF constituents must not be added to the portfolio denominator');
assert.equal(self.directPct,20);assert.equal(self.indirectPct,8);assert.ok(Math.abs(self.totalPct-28)<1e-10);
assert.equal(self.routes.length,1,'Multiple accounts for the same ETF are combined');
assert.equal(self.routes[0].etfValue,400);assert.equal(self.routes[0].value,80);
assert.ok(Math.abs(self.directShare-200/280*100)<1e-10);
assert.equal(self.directShare+self.indirectShare,100);
assert.equal(spouse.total,3000);assert.ok(Math.abs(spouse.totalPct-1400/3000*100)<1e-10);
assert.equal(ctx.etfExposure('NVDA',portfolio,data,'아내',now).length,1);
assert.equal(ctx.etfExposure('005930',portfolio,data,'본인',now)[0].indirectPct,4,'Indirect-only constituents count without a direct stock position');
const whole=ctx.etfExposure('NVDA',[row('본인','NVDA',300),row('본인','F',700,true)],{etfs:{F:s([h('NVDA',100)])}},'본인',now)[0];
assert.equal(whole.totalPct,100);assert.equal(whole.directShare,30);assert.equal(whole.indirectShare,70);
const empty=ctx.etfExposure('NVDA',[row('본인','NVDA',0)],data,'본인',now)[0];
assert.equal(empty.totalPct,null);assert.equal(empty.directShare,null);
assert.equal(ctx.etfExposure('NVDA',[row('본인','NVDA',Infinity)],data,'본인',now)[0].valid,false);
const partial={etfs:{F:s([h('OTHER',10)],{coverage:'partial',asOf:null})}};
assert.equal(ctx.etfExposure('NVDA',portfolio,partial,'본인',now)[0].uncertain.length,1);
ctx.cbAllRows=()=>[row('본인','F',100,true)];ctx.cbEtfDoc=()=>partial;
const unknownHtml=load(ctx.etfExposureHtml('NVDA',{t:'NVDA',n:'NVIDIA'}));
assert.equal(unknownHtml('.etf-exposure-total strong').text(),'미확인');
assert.match(unknownHtml('.etf-stock-split').text(),/비율 미확정/);
assert.equal(unknownHtml('details.etf-owner-exposure > summary.etf-owner-summary').length,1,'The complete owner card is a native keyboard-operable disclosure');
assert.equal(unknownHtml('details details').length,0,'No nested disclosure targets');
const toggleContext=vm.createContext({document:{activeElement:null},cbRestoreFilterFocus(){}});
vm.runInContext(fs.readFileSync('etf-explorer.js','utf8'),toggleContext);
vm.runInContext('etfRefreshResults=()=>{};cbRenderEtfExplorer=()=>{};',toggleContext);
toggleContext.etfSelect('NVDA');
assert.equal(vm.runInContext('_etfSelected',toggleContext),'NVDA');
toggleContext.etfSelect('NVDA');
assert.equal(vm.runInContext('_etfSelected',toggleContext),null,'A second click explicitly clears the stock instead of reselecting the first row');
toggleContext.etfOwner('본인');toggleContext.etfOwner('본인');
assert.equal(vm.runInContext('_etfOwner',toggleContext),'전체');
assert.equal(JSON.stringify({portfolio,data}),saved,'Exposure exploration does not mutate financial records or published snapshots');
const cobalt=fs.readFileSync('cobalt.js','utf8');
const loader=cobalt.slice(cobalt.indexOf('let _cbEtfPromise='),cobalt.indexOf('\nfunction cbIsEtf('));
let requests=0,fail=false;
const good={etfs:{F:current}};
const loadContext=vm.createContext({window:{},AbortController,setTimeout,clearTimeout,cbRerender(){},
  fetch:async()=>{requests++;if(fail)throw new Error('offline');return {ok:true,json:async()=>good};}});
vm.runInContext('let _cbEtfLoading=false;'+loader,loadContext);
await loadContext.cbEnsureEtfHoldings();assert.equal(requests,1);assert.equal(loadContext.window._etfHoldings,good);
await loadContext.cbEnsureEtfHoldings();assert.equal(requests,1,'Do not fetch again on every rerender');
fail=true;await loadContext.cbEnsureEtfHoldings(true);
assert.equal(loadContext.window._etfHoldings,good,'Failed refresh preserves the last valid file');
assert.equal(loadContext.window._etfLoadError,true);
fail=false;await loadContext.cbEnsureEtfHoldings(true);
assert.equal(requests,3);assert.equal(loadContext.window._etfLoadError,false,'Manual retry recovers');
console.log('PASS ETF freshness, company labels, owner portfolio denominators, direct/indirect exposure and incomplete-data safeguards');
